### ISSUE TITLE
if cloudformation error occurs, deploy blows up trying to destructure non-existent parameter

### ISSUE THREAD

**Issue by filmaj** [architect/deploy#12] opened 2019-08-02 15:30 UTC
if this error is triggered: https://github.com/architect/deploy/blob/master/src/sam/02-after/00-get-app-apex/reads.js#L25

it'll propagate up to here: https://github.com/architect/deploy/blob/master/src/sam/02-after/00-get-app-apex/index.js#L13

and the above function signature, if `err` exists but the second object parameter does not, will yield an error like:

```
  TypeError: Cannot destructure property `url` of 'undefined' or 'null'.
  at done (/Users/maj/src/cli/node_modules/@architect/deploy/src/sam/02-after/00-get-app-apex/index.js:12:16)
  at done (/Users/maj/src/cli/node_modules/@architect/deploy/src/sam/02-after/00-get-app-apex/reads.js:25:14)
```

**Comment by ryanblock** [comment] 2019-08-08 18:27
Can we re-scope the issue to check to ensure we have proper validation of presence of deploy bucket (and permissions), which was the root cause of the issue?

**Comment by brianleroux** [comment] 2019-08-09 20:36
closing dup of #1 / on it

**Comment by filmaj** [comment] 2019-08-12 14:20
Closing this issue without also changing the function signature leaves the underlying bug intact. If [this `reads` call](https://github.com/architect/deploy/blob/master/src/sam/02-after/00-get-app-apex/index.js#L9) invokes the error callback (e.g. [here](https://github.com/architect/deploy/blob/master/src/sam/02-after/00-get-app-apex/reads.js#L25)), it also does not pass an object as the second non-error parameter, [so the error callback will never invoke](https://github.com/architect/deploy/blob/master/src/sam/02-after/00-get-app-apex/index.js#L12-L13) as node will explode trying to destructure `undefined`.

To fix this bug, either need to ensure all error callback invocations inside `reads` also passes an object as a second parameter (not great), or change the function signature so that we don't destructure the object parameter when the callback may be invoked with an error (more code, but more robust IMO).

**Comment by brianleroux** [comment] 2019-08-12 14:31
Nope! Bug is fixed here https://github.com/architect/deploy/blob/master/src/validate/index.js but still need to integrate

**Comment by brianleroux** [comment] 2019-08-12 14:31
(we want errors!)

**Comment by brianleroux** [comment] 2019-08-12 14:32
Also, just for clarification, we def always want to bubble errors. Always!

**Comment by filmaj** [comment] 2019-08-12 14:49
I'm probably not explaining myself correctly, but in the code as is, if for whatever reason we get an error from [CloudFormation (either from describeStacks or from list)](https://github.com/architect/deploy/blob/master/src/sam/02-after/00-get-app-apex/reads.js#L13-L22), then the error will NOT bubble up due to the function signature [here](https://github.com/architect/deploy/blob/master/src/sam/02-after/00-get-app-apex/index.js#L12). Instead the error will be covered up by the destructuring failure.

Perhaps best explained with an example:

```
> (function(err, {one, two}) { if (err) console.error('error!') }).call(null, {error:true})
TypeError: Cannot destructure property `one` of 'undefined' or 'null'.
    at call.error (repl:1:10)
> (function(err, {one, two}) { if (err) console.error('error!') }).call(null, {error:true}, {})
error!
```

The first example is basically [what happens inside `reads`](https://github.com/architect/deploy/blob/master/src/sam/02-after/00-get-app-apex/reads.js#L25). The second example bubbles up the error but it requires the second parameter to be passed in.

**Comment by ryanblock** [comment] 2019-08-14 04:20
I've got a better understanding of this issue now, and yes, @filmaj is correct that we aren't bubbling errors correctly. Related, we've now seen 4 or 5 completely different scenarios where this bug has sprung up.

**Comment by ryanblock** [comment] 2019-08-14 21:41
Should now be fixed in https://github.com/architect/deploy/commit/5f9ef44d2632887bc36c6085f6fce08a3b05708a

More work to do to pretty this error reporting up more but at least it's the right error getting bubbled at the right time in the right way.

**Closed by ryanblock** 2019-08-14 21:41 UTC
Labels: bug
