### ISSUE TITLE
cannot be deployed w/o get-index handler

### ISSUE THREAD

**Issue by eshikerya** [architect/deploy#22] opened 2019-08-23 20:48 UTC
**Describe the issue**
If .arc have no ```get /``` entry, deploy fails with error "no get-index defined"

**Expected behavior**
deploy any routes project have, get-index should not be required

**Comment by ryanblock** [comment] 2019-10-10 22:33
I am unable to reproduce this behavior, closing for now. Please publish repro steps if you're still seeing it!

**Closed by ryanblock** 2019-10-10 22:33 UTC
